import type { Identifiers } from "./Identifiers";
import type { LeadershipSkills } from "./LeadershipSkills";
import type { Legalities } from "./Legalities";
import type { PurchaseUrls } from "./PurchaseUrls";
import type { RelatedCards } from "./RelatedCards";
import type { Rulings } from "./Rulings";

export type Card = {
  artist?: string;
  artistIds?: string[];
  cardParts?: string[];
  colorIdentity?: string[];
  colorIndicator?: string[];
  colors?: string[];
  defense?: string;
  edhrecRank?: number;
  edhrecSaltiness?: number;
  flavorName?: string;
  flavorText?: string;
  frameEffects?: string[];
  identifiers?: Identifiers;
  isFullArt?: boolean;
  isPromo?: boolean;
  isRebalanced?: boolean;
  isReserved?: boolean;
  isReprint?: boolean;
  isStarter?: boolean;
  isStorySpotlight?: boolean;
  isTextless?: boolean;
  keywords?: string[];
  layout?: string;
  leadershipSkills?: LeadershipSkills;
  legalities?: Legalities;
  life?: string;
  loyalty?: string;
  manaCost?: string;
  name?: string;
  number?: string;
  originalPrintings?: string[];
  otherFaceIds?: string[];
  power?: string;
  printings?: string[];
  promoTypes?: string[];
  purchaseUrls?: PurchaseUrls;
  rarity?: string;
  relatedCards?: RelatedCards;
  rebalancedPrintings?: string[];
  rulings?: Rulings[];
  securityStamp?: string;
  setCode?: string;
  subTypes?: string[];
  superTypes?: string[];
  text?: string;
  toughness?: string;
  type?: string;
  types?: string[];
  uuid: string;
  variations?: string[];
};